#pragma once

#include "quantum.h"
#include "luz/symbols.h"

// Luz's names for the keycodes its community modules (modules/luz/*, listed in each
// variant's keymap.json) define. The modules' own short aliases are CM_*; Luz keeps its
// historical, spelled-out names.
#define SK_UNDO       COMMUNITY_MODULE_SEMANTIC_UNDO
#define SK_CUT        COMMUNITY_MODULE_SEMANTIC_CUT
#define SK_COPY       COMMUNITY_MODULE_SEMANTIC_COPY
#define SK_PSTE       COMMUNITY_MODULE_SEMANTIC_PASTE
#define SK_EURO       COMMUNITY_MODULE_SEMANTIC_EURO
#define SK_CEDIL      COMMUNITY_MODULE_SEMANTIC_CEDILLA
#define SK_WORDPRV    COMMUNITY_MODULE_SEMANTIC_WORD_PREV
#define SK_WORDNXT    COMMUNITY_MODULE_SEMANTIC_WORD_NEXT
#define SK_LINEBEG    COMMUNITY_MODULE_SEMANTIC_LINE_BEGIN
#define SK_LINEEND    COMMUNITY_MODULE_SEMANTIC_LINE_END
#define SK_DELWORDPRV COMMUNITY_MODULE_SEMANTIC_DEL_WORD_PREV
#define SK_DELWORDNXT COMMUNITY_MODULE_SEMANTIC_DEL_WORD_NEXT
#define SK_DELLINEBEG COMMUNITY_MODULE_SEMANTIC_DEL_LINE_BEGIN
#define SK_DELLINEEND COMMUNITY_MODULE_SEMANTIC_DEL_LINE_END
#define SK_TABNEW     COMMUNITY_MODULE_SEMANTIC_TAB_NEW
#define SK_TABCLOSE   COMMUNITY_MODULE_SEMANTIC_TAB_CLOSE
#define SK_TABREOPEN  COMMUNITY_MODULE_SEMANTIC_TAB_REOPEN
#define SK_TABLEFT    COMMUNITY_MODULE_SEMANTIC_TAB_LEFT
#define SK_TABRIGHT   COMMUNITY_MODULE_SEMANTIC_TAB_RIGHT
#define SK_HISTPRV    COMMUNITY_MODULE_SEMANTIC_HISTORY_PREV
#define SK_HISTNXT    COMMUNITY_MODULE_SEMANTIC_HISTORY_NEXT
#define DK_ACUTE      COMMUNITY_MODULE_DEAD_ACUTE
#define DK_GRAVE      COMMUNITY_MODULE_DEAD_GRAVE
#define DK_CIRC       COMMUNITY_MODULE_DEAD_CIRC
#define DK_DIAE       COMMUNITY_MODULE_DEAD_DIAE
#define DK_TILDE      COMMUNITY_MODULE_DEAD_TILDE
#define SW_WIN        COMMUNITY_MODULE_SWAPPER
#define SW_OS         COMMUNITY_MODULE_HOST_OS_TOGGLE
#define PR_OS         COMMUNITY_MODULE_HOST_OS_PRINT

// Luz's own keycodes.
enum custom_keycodes {
    MD_FENCE = SAFE_RANGE,   // Markdown code fence: types ```
    ARROW_OP,                // Tap: ->  Shift: =>

    // Symbol keycodes (expanded from SYMBOLS_LIST, luz/symbols.h)
    SYMBOLS_LIST,
};
